### PR TITLE
cmake build system.

### PR DESCRIPTION
**Pull request by juj**
Disable PTHREADS being default on in Emscripten builds, since JavaScript/Emscripten does not yet have pthreads support.

### CODE REVIEW

**Comment by gsathya** [comment]
@juj Should I go ahead and merge this? or wait until all the cmake bits are fixed?

**Comment by juj** [comment]
No hurry, we can keep this open until the cmake part is mature and then merge.

**Comment by juj** [comment]
The CMake improvements to Emscripten were merged, and this should be now good for merging as well.

**Comment by gsathya** [comment]
Sweet, thanks!

**Comment by mtsr** [comment]
I still have a problem when building SDL-emscripten with cmake. I call cmake like this:

```
cmake -DCMAKE_TOOLCHAIN_FILE=~/Development/emsdk-portable/emscripten/1.21.0/cmake/Platform/Emscripten.cmake \
-DEMSCRIPTEN=ON \
-G "Unix Makefiles" \
..
```

But then I get an error building SDL_string.c

```
Building C object SDL/CMakeFiles/SDL2-static.dir/src/stdlib/SDL_string.c.o
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:541:12: error: implicit declaration
      of function '_strrev' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return _strrev(string);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:541:12: warning: incompatible
      integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
    return _strrev(string);
           ^~~~~~~~~~~~~~~
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:560:12: error: implicit declaration
      of function '_strupr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return _strupr(string);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:560:12: note: did you mean
      'strupr'?
    return _strupr(string);
           ^~~~~~~
           strupr
/Users/<username>/Development/emsdk-portable/emscripten/1.21.0/system/include/compat/string.h:9:14: note: 
      'strupr' declared here
extern char* strupr(char *);
             ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:560:12: warning: incompatible
      integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
    return _strupr(string);
           ^~~~~~~~~~~~~~~
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:575:12: error: implicit declaration
      of function '_strlwr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return _strlwr(string);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:575:12: note: did you mean
      'strlwr'?
    return _strlwr(string);
           ^~~~~~~
           strlwr
/Users/<username>/Development/emsdk-portable/emscripten/1.21.0/system/include/compat/string.h:8:14: note: 
      'strlwr' declared here
extern char* strlwr(char *);
             ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:575:12: warning: incompatible
      integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
    return _strlwr(string);
           ^~~~~~~~~~~~~~~
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:654:12: error: implicit declaration
      of function 'itoa' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return itoa(value, string, radix);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:654:12: warning: incompatible
      integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
    return itoa(value, string, radix);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:664:12: error: implicit declaration
      of function '_uitoa' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return _uitoa(value, string, radix);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:664:12: note: did you mean 'itoa'?
    return _uitoa(value, string, radix);
           ^~~~~~
           itoa
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:654:12: note: 'itoa' declared here
    return itoa(value, string, radix);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:664:12: warning: incompatible
      integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
    return _uitoa(value, string, radix);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:674:12: error: implicit declaration
      of function '_ltoa' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return _ltoa(value, string, radix);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:674:12: warning: incompatible
      integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
    return _ltoa(value, string, radix);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:693:12: error: implicit declaration
      of function '_ultoa' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return _ultoa(value, string, radix);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:693:12: warning: incompatible
      integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
    return _ultoa(value, string, radix);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:718:12: error: implicit declaration
      of function '_i64toa' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return _i64toa(value, string, radix);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:718:12: warning: incompatible
      integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
    return _i64toa(value, string, radix);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:737:12: error: implicit declaration
      of function '_ui64toa' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return _ui64toa(value, string, radix);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:737:12: note: did you mean
      '_i64toa'?
    return _ui64toa(value, string, radix);
           ^~~~~~~~
           _i64toa
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:718:12: note: '_i64toa' declared
      here
    return _i64toa(value, string, radix);
           ^
/Users/<username>/Development/SDL-emscripten/src/stdlib/SDL_string.c:737:12: warning: incompatible
      integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
    return _ui64toa(value, string, radix);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
9 warnings and 9 errors generated.
```

It's odd, since _strrev (and others) are being found by cmake:

```
-- Looking for _strrev
-- Looking for _strrev - found
```

emnconfigure & emmake works, with the additional settings as in the read me.

**Comment by juj** [comment]
There were a number of fixes that had to go in to Emscripten itself, the 1.21.0 release doesn't have them. Try switching to the `incoming` sdk version to build the current trunk instead, that has the CMake fixes in.

**Comment by mtsr** [comment]
Thanks! That helps.

**Pull request merged**
